### PR TITLE
added necessary dependencies/configurations. added main page and nece…

### PR DESCRIPTION
**Pull request by mdlaroy**
…ssary linked pages

In this pull request, I added some necessary configurations and dependencies. I installed TypeScript and changed all of our base .js files to .tsx if necessary. I altered the tailwind.config.js
I also created the tsconfig.json.

The LandingPage with a carousel has been created. I also created a bio and name tag. Additionally, the nav bar at the bottom has been created and all buttons link to the blank pages associated with them.

### CODE REVIEW

**Comment by mdlaroy** [comment]
> Hi Megan. amazing work so far. it is good that you changed the base js to tsx since we made the change to typescript. I only have one concern that I can see and that is about how changing to typescript, as we change the other dependencies and configurations it may potentially cause cohesion issue with the app.

@abhagat8 you are completely right about that! I definitely agree all the new dependencies/configurations I made, could potentially pose problems. After everyone can merge and install the updated dependencies, I believe it should function as expected. I installed a compatible version of TypeScript and altered the existing files to tsx as necessary.

**Comment by mdlaroy** [comment]
> Hello Megan, the UI is coming together there are a few things that I noticed that needs a little fixing on the placement as in the settings icon. Also ensure that the UI tailors towards phone sizing.

Rami, thanks for the feedback! I did misplace the settings button, I was having issues with it in the header but I plan to amend that. For the UI, after we deploy, I will definitely be checking if it tailors to the phone sizing as I know tailwind has a mobile-first breakpoint system!

**Review by linchristina03 — COMMENTED** [review]
Good evening Megan! Glad to see that your UI is coming along and working with tailwind!  
We will definitely meet up to make sure the UI design is cohesive and that our configurations are the same (it not much different from mine but just to make sure we have the same overall theme of the application). Overall, I like the carousel and I'm sure you'll be adding more information on the other pages in the future, when we get to them.
Thanks for taking the time to work on the UI of the Main Page!

**Comment by mdlaroy** [comment]
> Good evening Megan! Glad to see that your UI is coming along and working with tailwind! We will definitely meet up to make sure the UI design is cohesive and that our configurations are the same (it not much different from mine but just to make sure we have the same overall theme of the application). Overall, I like the carousel and I'm sure you'll be adding more information on the other pages in the future, when we get to them. Thanks for taking the time to work on the UI of the Main Page!

Good evening! Thanks for touching base, we will definitely chat more about the UI design like you mentioned. And yes, the other pages will be in issues down the line but I wanted to establish the base pages so the buttons would link to the appropriate place for now!

**Pull request merged**
