### PR TITLE
Added login and create login functions

### PR DESCRIPTION
**Pull request by RamiDari15**
In this Pull Request i have changed the sever.js file adding two new methods inside. I created two post methods. The first post method is creating login information which ensures that the email and password field is filled in, they are valid emails that end with @emich, and they are emails never used before with our application. The second post method validates the login email and password with the firestore database.

### CODE REVIEW

**Comment by abhagat8** [comment]
Hi Rami, thank you for adding the post method to your code. With that and the way I have the database setup right now, we can finally run some test to make sure the authorization is working correctly  and have our login system set.

**Comment by RamiDari15** [comment]
@abhagat8 I seen the database and agree that we do enough to merge both this weekend to test if the database and code connects

**Comment by mdlaroy** [comment]
Rami, awesome work on creating this so far. It was smart to check to make sure the emails haven't already been used! Maybe we could include more verbose error messaging so the user can be pointed in a more clear direction if they have an issue that isn't so obvious :) Thank you for taking the time to work on this!

**Comment by RamiDari15** [comment]
@mdlaroy thank you for your feedback I will work on adding the more clear instruction on what to do when a user needs the correct input

**Review by linchristina03 — COMMENTED** [review]
Good evening Rami! I like the direction that the login authentication on the backend is coming along. The duplicate user check I completely overlooked so I appreciate you being able to catch it on the backend side. My only change would be for new users there are going to be a lot more fields and may no necessarily be needed for login verification (we may need 2 places for authentication, sign up & login separate maybe?). Let's meet sometime before Wednesday to make sure that my login page and our authenticator can work together cohesively. Thank you for taking you time to work on the authenticator!

**Comment by RamiDari15** [comment]
@linchristina03 thank you for your input i'll work on adding those field into the backend check

**Pull request merged**
