### PR TITLE
Basic Login page created

### PR DESCRIPTION
**Pull request by linchristina03**
fix: create basic login page

*Note: this was created before the main base layer was completed.*

This commit adds the base layer for the login page including:
- Created basic UI page
- Created Text boxes to enter the user name (currently email only) and password
- --Username will verify if the end is an @emich.edu address and make sure neither fields are blank.
- created a link/button to register/signup (no page linked
- created a link/button to reset password (no page linked)
- created a login button (no page linked)
- created a signup button (no page linked)
- This commit includes the configurations & dependencies for tailwind.css but are subject to change.

Fixes needed: tailwind does not work as coded. button should have colors and other css styling. will need to reconfig to make it the proper layout design. links do not redirect yet.

addresses: 2,3,4,6

### CODE REVIEW

**Comment by mdlaroy** [comment]
Christina! Thank you for starting this even though you have been so busy. I should have gotten with you about what I did for the tailwind, that is my bad! We will link up sometime so we can establish a more uniform design. Great work and thanks again :D

**Comment by abhagat8** [comment]
Hello Christina, this is very good job on getting the UI for the login page ready. I think rami has the authorization good to go as well, along with that the database is also all set to hold the user login information so it will be good to connect all the pieces this weekend hopefully.

**Comment by RamiDari15** [comment]
Hello christina this is a good start for the UI page as the weekend goes wehould work on merging the methods I have in the UI you created.

**Comment by linchristina03** [comment]
> Christina! Thank you for starting this even though you have been so busy. I should have gotten with you about what I did for the tailwind, that is my bad! We will link up sometime so we can establish a more uniform design. Great work and thanks again :D

No worries! I'll do my best to allocate sometime to meetup as soon as possible. Thanks!

**Comment by linchristina03** [comment]
> Hello Christina, this is very good job on getting the UI for the login page ready. I think rami has the authorization good to go as well, along with that the database is also all set to hold the user login information so it will be good to connect all the pieces this weekend hopefully.

Awesome, I'm hoping there's a good time for all of us to meet together to connect the pieces. thanks again!

**Comment by linchristina03** [comment]
> Hello christina this is a good start for the UI page as the weekend goes we hould work on merging the methods I have in the Login page you created.

Thanks Rami! we will definitely make time to merge our methods together so that they work seamlessly.

**Pull request merged**
