### PR TITLE
Commit for PBI1:setup database-Dummy tests

### PR DESCRIPTION
**Pull request by abhagat8**
fix: Setup our database
This Pull Request tests if the database is properly setup. In Firestore I setup the database and I made dummy tests to ensure communication with the database is working properly. 

I made a file called addUser.js that allows us to add user information to the database. 
I made  another file called getUserInfo.js that allows to get information related to a user from data. 
lastly the file called firebase-config.js that is just the config file for our firebase database.  

these file's main point is to make sure that the database we setup in firebase can be communicated with, hence the we made dummy calls to it via these files. this way we can ensure that when our users login or make an account we can store there information properly.

### CODE REVIEW

**Comment by RamiDari15** [comment]
Hello Abhi I seen the databases you have setup, I do think it woud be a good idea to add additional fields for the user collection to add more depth in the database. As well as looking towards other apps to see if theres additional users prefrence page things you could add

**Comment by abhagat8** [comment]
@RamiDari15 hi Rami, thank you for the feedback and your completely right I was going to add more collections to the database as my next step after the dummy tests. I want to add fields for preferences settings like dark mode, light mode, nonfictions, and the chats, etc.

**Comment by mdlaroy** [comment]
Abhi, great work setting up the beginnings of the database. Like Rami mentioned, we definitely need to add more fields for all the necessary configurations. Aside from just settings, it could be useful to have fields for the personal user information such as age, major, phone number, etc. Thank you for setting this up!

**Review by linchristina03 — CHANGES_REQUESTED** [review]
Good evening Abhi! Thanks for taking the time to address the Database PBI. As already mentioned we will need more fields to store all the necessary preferences/demographic information, but I understand that the only 3 fields are the username/email and password. Overall clean and organized. Over the next few days, I would like to meet with you to make sure that my login page will be able to send the data to your database through Rami's login authentication, before merging. Thanks!

**Comment by abhagat8** [comment]
@mdlaroy Megan, I agree with you completely that is my goal for this weekend to add more field to the database. Thank you for the user personal information suggest I will take that into account!

**Comment by abhagat8** [comment]
@linchristina03 Christina thank you for your feedback, I think it will be a good idea to meetup. In the next few days we should meet along with Rami who has the authorization ready to connect all our pieces together and make sure the login process is set. Also it is also my goal to add more field in the database this weekend well.

**Pull request merged**
